before_script:
  - sudo apt install steamcmd

build1:
  stage: build
  script:
    - wget https://github.com/SteamRE/DepotDownloader/releases/download/DepotDownloader_2.3.6/depotdownloader-2.3.6.zip
    - unzip depotdownloader-2.3.6.zip