build1:
  stage: build
  script:
    - mkdir ore_trader_improved
    - mv * ore_trader_improved
    - wget https://dot.net/v1/dotnet-install.sh
    - chmod +x dotnet-install.sh
    - ./dotnet-install.sh --runtime dotnet --install-dir ./
    - wget https://github.com/SteamRE/DepotDownloader/releases/download/DepotDownloader_2.3.6/depotdownloader-2.3.6.zip
    - unzip -o depotdownloader-2.3.6.zip
    - chmod +x depotdownloader
    - ./dotnet DepotDownloader.dll -app 677120 -depot 677122 -username $STM_USER -password $STM_PASS
    - cd depots/677122/4737785/
    - ./PACKAGER.exe --resources=../../../ore_trader_improved --destination=ore_trader_improved.bin
    - ls
    - cd ../../../
    - ls