<!-- Widebois -->
<sprite name="thyraxx-scalebutton-left" texture="gui/thyraxx_buttons.png"><frame>0 0 16 28</frame></sprite>
<sprite name="thyraxx-scalebutton-mid" texture="gui/thyraxx_buttons.png"><frame>16 0 1 28</frame></sprite>
<sprite name="thyraxx-scalebutton-right" texture="gui/thyraxx_buttons.png"><frame>17 0 16 28</frame></sprite>

<sprite name="thyraxx-scalebutton-hover-left" texture="gui/thyraxx_buttons.png"><frame>0 28 16 28</frame></sprite>
<sprite name="thyraxx-scalebutton-hover-mid" texture="gui/thyraxx_buttons.png"><frame>16 28 1 28</frame></sprite>
<sprite name="thyraxx-scalebutton-hover-right" texture="gui/thyraxx_buttons.png"><frame>17 28 16 28</frame></sprite>

<sprite name="thyraxx-scalebutton-down-left" texture="gui/thyraxx_buttons.png"><frame>0 56 16 28</frame></sprite>
<sprite name="thyraxx-scalebutton-down-mid" texture="gui/thyraxx_buttons.png"><frame>16 56 1 28</frame></sprite>
<sprite name="thyraxx-scalebutton-down-right" texture="gui/thyraxx_buttons.png"><frame>17 56 16 28</frame></sprite>

<!-- Regular disabled -->
<sprite name="thyraxx-scalebutton-disabled-left" texture="gui/thyraxx_buttons.png"><frame>0 84 16 28</frame></sprite>
<sprite name="thyraxx-scalebutton-disabled-mid" texture="gui/thyraxx_buttons.png"><frame>16 84 1 28</frame></sprite>
<sprite name="thyraxx-scalebutton-disabled-right" texture="gui/thyraxx_buttons.png"><frame>17 84 16 28</frame></sprite>
